### ISSUE TITLE
Crash Caused by this mod

### ISSUE THREAD

**Issue by Killercrab432** [Khajiitos/ISWYDT#3] opened 2024-03-04 04:34 UTC
https://pastebin.com/JyDHmLBB received a crash caused by this mod, wasnt really doing anything at the time it happened was just walking into cows in creative, any idea what causes this or how i can prevent it in the future?

**Comment by Khajiitos** [comment] 2024-03-04 17:47
Might be caused by an unexpected incompatibility with [Neruina](https://www.curseforge.com/minecraft/mc-mods/neruina), I will look further into it.

**Comment by Khajiitos** [comment] 2024-03-04 21:12
I was walking around and pushing cows as well, but I couldn't get the game to crash, even with the Neruina mod installed. Maybe the mod is actually unrelated to this issue, it might appear in the crash log only because it wraps tick code.

Can you see if you can get the game to crash consistently, or was it just a rare one-off?

**Comment by Killercrab432** [comment] 2024-03-05 07:29
Was likely a rare one off, it has not happened since

**Comment by Killercrab432** [comment] 2024-03-05 11:31
Nevermind just got it again this time i was literally doing nothing just running through an empty field https://pastebin.com/1dQmxuGZ

**Comment by Khajiitos** [comment] 2024-03-06 08:41
But I feel like Neruina might be the culprit. Maybe it runs ticks in parallel, which creates a race condition that is pretty much unpreventable. If we can get this mod to crash without Neruina, then it's most likely an issue purely with this mod.

**Comment by Killercrab432** [comment] 2024-03-07 05:02
couldnt replicate it when not using Neruina so opening up an issue over there

**Comment by Bawnorton** [comment] 2024-03-07 05:11
this is caused here:
https://github.com/Khajiitos/ISWYDT/blob/master/Common/src/main/java/me/khajiitos/iswydt/common/mixin/BlockMixin.java#L27

This method is called on the client and server thread, thus, in a singleplayer world there is a non-zero chance that one thread will be iterating over the list when the other thread encounters it.

Please ensure that game logic only runs on the server thread, and if you are going to iterate over a collection on both threads, ensure it's a synchronised collection.

**Comment by Khajiitos** [comment] 2024-03-07 11:05
Right, that makes sense, I forgot that both the client side and the server side have access to the same list on singleplayer. Will fix it soon!

**Comment by Khajiitos** [comment] 2024-03-10 19:55
This might be fixed in the 1.0.4 version of the mod.

**Closed as completed by Khajiitos** 2024-03-10 19:55 UTC

**Comment by Killercrab432** [comment] 2024-03-11 01:07
Awesome news thanks for the speedy assistance
