### ISSUE TITLE
Crash with moonlight 1.20.1

### ISSUE THREAD

**Issue by mxnmnm** [Khajiitos/ISWYDT#6] opened 2024-04-05 04:46 UTC
https://gist.github.com/mxnmnm/192d24c6d4c38f7a12288760d5adc4d4

I tried logging into a dedicated server and the server crashed.

**Comment by Khajiitos** [comment] 2024-04-06 07:23
I think this is not directly caused by the Moonlight mod, but dispensing water in general causes the crash. I will fix it soon, thanks for reporting

**Comment by Khajiitos** [comment] 2024-04-07 17:59
This should now be fixed in the 1.0.5 version of the mod. Thanks for reporting!

**Closed as completed by Khajiitos** 2024-04-07 17:59 UTC
